import argparse
import requests

def main(argv):
    files = {
        'file': (argv.input, open(argv.input, 'rb')),
        'training_id': (None, str(argv.run)),
        'layers': (None, str(argv.blocks)),
        'filters': (None, str(argv.filters)),
    }
    response = requests.post(argv.upload, files=files)
    print(response)
    print(response.text)


if __name__ == "__main__":
    argparser = argparse.ArgumentParser(description=\
            'Rename files generated by lc0 to have training names.')
    argparser.add_argument('-i', '--input', type=str, help='input file')
    argparser.add_argument('-u', '--upload', type=str, help='uploadurl')
    argparser.add_argument('-f', '--filters', type=int, help='filters')
    argparser.add_argument('-b', '--blocks', type=int, help='blocks')
    argparser.add_argument('-r', '--run', type=int, help='training run')

    main(argparser.parse_args())
